application: yhack-sms 
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /alarmcall
  static_files: alarmcall.xml
  upload: alarmcall\.xml

- url: .*
  script: yalesms.app

libraries:
- name: webapp2
  version: "2.5.2"
